Resources:
  ExampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: examplepoc
      AttributeDefinitions:
        - AttributeName: ida
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
